CWB: utils/cwb-seek-structures.php File Reference
cwb-seek-structures.php File Reference
Data Structures
class XmlElement
Functions
seekstructures_get_structure_index ($el)
seekstructures_print_result ()
seekstructures_usage ()
main ($argc, $argv)
Variables
$xml_found = array()
Function Documentation
main ($argc, $argv)
References $xml_found, seekstructures_get_structure_index(), seekstructures_print_result(), and seekstructures_usage().
seekstructures_get_structure_index ($el)
References $xml_found.
Referenced by main().
seekstructures_print_result ()
References $xml_found.
Referenced by main().
seekstructures_usage ()
Referenced by main().
Variable Documentation
$xml_found = array()
Referenced by main(), seekstructures_get_structure_index(), and seekstructures_print_result().