CWB: cqp/dummy_auth.c File Reference
dummy_auth.c File Reference
All functions in this module are dummy implementations which just print an error message.
#include "../CQi/auth.h"
#include "output.h"
Functions
void add_user_to_list (char *user, char *passwd)
void add_grant_to_last_user (char *corpus)
void add_host_to_list (char *ipaddr)
void add_hosts_in_subnet_to_list (char *ipsubnet)
int check_host (struct in_addr host_addr)
returns true if host is in list of allowed hosts
int authenticate_user (char *username, char *passwd)
returns true if (user, passwd) pair is in list of allowed users
int check_grant (char *username, char *corpus)
returns true if user may access corpus
void show_grants (void)
for debugging only
Detailed Description
All functions in this module are dummy implementations which just print an error message.
Function Documentation
void add_grant_to_last_user (char * corpus)
References cl_malloc(), cl_strdup(), _Grant::corpus, _UserEntry::grants, and _Grant::next.
void add_host_to_list (char * ipaddr)
References _HostEntry::accept_any, _HostEntry::address, authorized_hosts, cl_malloc(), cqpmessage(), Error, and _HostEntry::next.
void add_hosts_in_subnet_to_list (char * ipsubnet)
References add_host_to_list(), cl_free, cl_malloc(), cqpmessage(), and Error.
void add_user_to_list (char * user, char * passwd)
References authorized_users, cl_malloc(), cl_strdup(), cqpmessage(), Error, find_user(), _UserEntry::grants, _UserEntry::name, _UserEntry::next, and _UserEntry::passwd.
int authenticate_user (char * username, char * passwd)
returns true if (user, passwd) pair is in list of allowed users
References find_user(), _UserEntry::passwd, and user.
int check_grant (char * username, char * corpus)
returns true if user may access corpus
References _Grant::corpus, find_user(), _UserEntry::grants, _Grant::next, and user.
int check_host (struct in_addr host_addr)
returns true if host is in list of allowed hosts
References _HostEntry::accept_any, _HostEntry::address, and _HostEntry::next.
void show_grants (void)
for debugging only
References _HostEntry::address, _Grant::corpus, _UserEntry::grants, _UserEntry::name, _Grant::next, _UserEntry::next, _HostEntry::next, _UserEntry::passwd, and user.