CWB: cl/globals.c File Reference
globals.c File Reference
#include "globals.h"
Functions
void cl_set_debug_level (int level)
Sets the debug level configuration variable.
void cl_set_optimize (int state)
Turns optimization on or off.
void cl_set_memory_limit (int megabytes)
Sets the memory limit respected by some CL functions.
Variables
int cl_debug = 0
global configuration variable: debug level.
int cl_optimize = 0
global configuration variable: optimisation.
size_t cl_memory_limit = 0
global configuration variable: memory limit.
Function Documentation
void cl_set_debug_level (int level)
Sets the debug level configuration variable.
See also
cl_debug
References cl_debug.
Referenced by execute_side_effects(), main(), parse_options(), and set_default_option_values().
void cl_set_memory_limit (int megabytes)
Sets the memory limit respected by some CL functions.
See also
cl_memory_limit
References cl_memory_limit.
Referenced by main().
void cl_set_optimize (int state)
Turns optimization on or off.
See also
cl_optimize
Parameters
state Boolean (true turns it on, false turns it off).
References cl_optimize.
Referenced by execute_side_effects(), main(), and set_default_option_values().
Variable Documentation
int cl_debug = 0
global configuration variable: debug level.
Controls how many debug messages are printed.
0 = none (default), 1 = some, 2 = heavy
Referenced by cl_lexhash_check_grow(), cl_new_regex(), cl_ngram_hash_check_grow(), cl_regex2id(), cl_regex_match(), cl_regopt_analyse(), cl_set_debug_level(), creat_rev_corpus(), create_component(), make_jump_table(), and regopt_data_copy_to_regex_object().
size_t cl_memory_limit = 0
global configuration variable: memory limit.
In megabytes; some functions will try to keep to this limit; 0 or less turns the limit off.
(ensure memory limit > 2GB is correctly converted to byte size or number of ints)
Referenced by cl_set_memory_limit(), and creat_rev_corpus().
int cl_optimize = 0
global configuration variable: optimisation.
0 = off, 1 = on (untested / expensive optimisations)
Referenced by cl_regex_match(), and cl_set_optimize().