CWB: cqp/html-print.c File Reference
html-print.c File Reference
#include "html-print.h"
#include <stdio.h>
#include <string.h>
#include "../cl/macros.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/cdaccess.h"
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include "cqp.h"
#include "options.h"
#include "corpmanag.h"
#include "concordance.h"
#include "attlist.h"
#include "print_align.h"
#include <sys/time.h>
#include <time.h>
#include <pwd.h>
Functions
char * html_print_field (FieldType field, int start)
void html_puts (FILE *fd, char *s, int flags)
char * html_convert_string (char *s)
void html_print_aligned_line (FILE *stream, char *attribute_name, char *line)
Prints a line of text (which will have been previously extracted from a corpus linked to the present corpus by an a-attribute) within HTML markup.
void html_print_context (ContextDescriptor *cd, FILE *stream)
void html_print_corpus_header (CorpusList *cl, FILE *stream)
void html_print_output (CorpusList *cl, FILE *stream, int interactive, ContextDescriptor *cd, int first, int last)
void html_print_group (Group *group, int expand, FILE *fd)
Variables
PrintDescriptionRecord HTMLPrintDescriptionRecord
PrintDescriptionRecord HTMLTabularPrintDescriptionRecord
PrintDescriptionRecord HTMLTabularNowrapPrintDescriptionRecord
Function Documentation
char* html_convert_string (char * s)
References CL_MAX_LINE_LENGTH.
void html_print_aligned_line (FILE * stream, char * attribute_name, char * line)
Prints a line of text (which will have been previously extracted from a corpus linked to the present corpus by an a-attribute) within HTML markup.
Parameters
stream Destination for the output.
attribute_name The name of the aligned corpus: printed in the leading indicator within the HTML.
line Character data of the line of aligned-corpus data to print. This is treated as opaque.
References GlobalPrintOptions, html_puts(), _print_option_rec_::print_tabular, _print_option_rec_::print_wrap, SUBST_ALL, and SUBST_NONE.
Referenced by printAlignedStrings().
void html_print_context (ContextDescriptor * cd, FILE * stream)
References CHAR_CONTEXT, _context_description_block::left_structure_name, _context_description_block::left_type, _context_description_block::left_width, _context_description_block::right_structure_name, _context_description_block::right_type, _context_description_block::right_width, STRUC_CONTEXT, and WORD_CONTEXT.
Referenced by html_print_corpus_header().
void html_print_corpus_header (CorpusList * cl, FILE * stream)
References CD, cl::corpus, GlobalPrintOptions, html_print_context(), cl::mother_name, TCorpus::name, cl::name, passwd, _print_option_rec_::print_header, cl::query_corpus, cl::query_text, TCorpus::registry_name, and cl::size.
Referenced by print_corpus_info_header().
char * html_print_field (FieldType field, int start)
References GlobalPrintOptions, KeywordField, MatchField, NoField, _print_option_rec_::print_tabular, _print_option_rec_::print_wrap, and TargetField.
void html_print_group (Group * group, int expand, FILE * fd)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), html_puts(), _grouptable::nr_cells, _id_cnt_mapping::s, SUBST_ALL, and _id_cnt_mapping::t.
Referenced by print_group().
void html_print_output (CorpusList * cl, FILE * stream, int interactive, ContextDescriptor * cd, int first, int last)
References _print_descr_rec_::AfterConcordance, _print_descr_rec_::AfterLine, _context_description_block::alignedCorpora, _print_descr_rec_::BeforeLine, CD, cl_broken_pipe, compose_kwic_line(), ConcLineHorizontal, cl::corpus, _Range::end, _ConcLineField::end_position, GlobalPrintOptions, HTMLPrintDescriptionRecord, HTMLTabularNowrapPrintDescriptionRecord, HTMLTabularPrintDescriptionRecord, KeywordField, cl::keywords, last, line, MatchEndField, MatchField, NoField, ParsePrintOptions(), _print_option_rec_::print_border, _print_option_rec_::print_tabular, _print_option_rec_::print_wrap, printAlignedStrings(), _context_description_block::printStructureTags, cl::range, cl::size, cl::sortidx, _Range::start, _ConcLineField::start_position, TargetField, cl::targets, and _ConcLineField::type.
Referenced by print_output().
void html_puts (FILE * fd, char * s, int flags)
References SUBST_AMP, SUBST_GT, SUBST_LT, and SUBST_QUOT.
Referenced by html_print_aligned_line(), and html_print_group().
Variable Documentation
PrintDescriptionRecord HTMLPrintDescriptionRecord
Referenced by html_print_output(), and printAlignedStrings().
PrintDescriptionRecord HTMLTabularNowrapPrintDescriptionRecord
Referenced by html_print_output().
PrintDescriptionRecord HTMLTabularPrintDescriptionRecord
Referenced by html_print_output().