CWB: cqp/latex-print.h File Reference
latex-print.h File Reference
#include <stdio.h>
#include "../cl/bitfields.h"
#include "corpmanag.h"
#include "context_descriptor.h"
#include "print-modes.h"
#include "groups.h"
Functions
char * latex_convert_string (char *s)
void latex_print_aligned_line (FILE *stream, char *attribute_name, char *line)
Does nothing: we don't support printing alignment data in LaTeX mode.
void latex_print_corpus_header (CorpusList *cl, FILE *outfd)
void latex_print_output (CorpusList *cl, FILE *outfd, int interactive, ContextDescriptor *cd, int first, int last)
void latex_print_group (Group *group, int expand, FILE *fd)
Variables
PrintDescriptionRecord LaTeXPrintDescriptionRecord
Function Documentation
char* latex_convert_string (char * s)
References CL_MAX_LINE_LENGTH.
Referenced by latex_print_group().
void latex_print_aligned_line (FILE * stream, char * attribute_name, char * line)
Does nothing: we don't support printing alignment data in LaTeX mode.
Parameters
stream Destination for the output.
attribute_name The name of the aligned corpus.
line Character data of the line of aligned-corpus data to print.
Referenced by printAlignedStrings().
void latex_print_corpus_header (CorpusList * cl, FILE * outfd)
References CD, cl::corpus, latex_print_context(), cl::mother_name, TCorpus::name, cl::name, passwd, TCorpus::registry_name, and cl::size.
Referenced by print_corpus_info_header().
void latex_print_group (Group * group, int expand, FILE * fd)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), latex_convert_string(), _grouptable::nr_cells, _id_cnt_mapping::s, and _id_cnt_mapping::t.
Referenced by print_group().
void latex_print_output (CorpusList * cl, FILE * outfd, int interactive, ContextDescriptor * cd, int first, int last)
References _print_descr_rec_::AfterConcordance, _print_descr_rec_::AfterLine, _context_description_block::alignedCorpora, _print_descr_rec_::BeforeConcordance, _print_descr_rec_::BeforeLine, CD, cl_broken_pipe, compose_kwic_line(), ConcLineHorizontal, cl::corpus, _Range::end, _ConcLineField::end_position, GlobalPrintOptions, KeywordField, cl::keywords, last, LaTeXPrintDescriptionRecord, LaTeXTabularPrintDescriptionRecord, line, _attlist::list, MatchEndField, MatchField, _attrbuf::next, NoField, ParsePrintOptions(), _print_option_rec_::print_border, _context_description_block::print_cpos, _print_option_rec_::print_tabular, printAlignedStrings(), _context_description_block::printStructureTags, cl::range, cl::size, cl::sortidx, _Range::start, _ConcLineField::start_position, _attrbuf::status, TargetField, cl::targets, and _ConcLineField::type.
Referenced by print_output().
Variable Documentation
PrintDescriptionRecord LaTeXPrintDescriptionRecord
Referenced by latex_print_output(), and printAlignedStrings().