CWB: cqp/print-modes.h File Reference
print-modes.h File Reference
#include "corpmanag.h"
#include "attlist.h"
Data Structures
struct _print_option_rec_
PrintOptions: records a set of print options.
struct _print_descr_rec_
The PrintDescriptionRecord object.
Typedefs
typedef enum outputmode PrintMode
Print mode: specifies output formats for CQP.
typedef struct _print_option_rec_ PrintOptions
PrintOptions: records a set of print options.
typedef struct _print_descr_rec_ PrintDescriptionRecord
The PrintDescriptionRecord object.
typedef char *(* TokenEscapeFunction)(char *)
Enumerations
enum outputmode {
PrintASCII, PrintSGML, PrintHTML, PrintLATEX,
PrintBINARY, PrintUNKNOWN
}
Print mode: specifies output formats for CQP.
Functions
AttributeList * ComputePrintStructures (CorpusList *cl)
Computes a list of s-attributes to print from the PrintStructure global option setting.
void ParsePrintOptions (void)
Reads the global string printModeOptions and parses it to update the GlobalPrintOptions.
void CopyPrintOptions (PrintOptions *target, PrintOptions *source)
Copies a PrintOptions object.
Variables
PrintMode GlobalPrintMode
Global print-mode setting.
PrintOptions GlobalPrintOptions
Global print-options: all booleans initially set to false.
Typedef Documentation
typedef struct _print_descr_rec_ PrintDescriptionRecord
The PrintDescriptionRecord object.
Contains strings / function pointers that control the printing mode (esp. the format of an individual concordance line).
Note that currently it is not possible for a new PDR to be defined at runtime. It must be done at compile-time.
typedef enum outputmode PrintMode
Print mode: specifies output formats for CQP.
typedef struct _print_option_rec_ PrintOptions
PrintOptions: records a set of print options.
All members starting in print_ are Boolean, to be interpreted as print_XX –> "XX is to be printed"
typedef char*(* TokenEscapeFunction)(char *)
Enumeration Type Documentation
enum outputmode
Print mode: specifies output formats for CQP.
Enumerator
PrintASCII
PrintSGML
PrintHTML
PrintLATEX
PrintBINARY
PrintUNKNOWN
Function Documentation
AttributeList* ComputePrintStructures (CorpusList * cl)
Computes a list of s-attributes to print from the PrintStructure global option setting.
PrintStructure is itself updated.
Parameters
cl The corpus from which to find the attributes.
Returns
An attribute list containing the attributes to be printed.
References AddNameToAL(), _Attribute::any, ATT_STRUC, _attrbuf::attribute, cl::corpus, cqpmessage(), DestroyAttributeList(), Error, find_attribute, _attlist::list, NewAttributeList(), _attrbuf::next, PRINT_STRUC_SEP, printStructure, TCorpus::registry_name, structure_has_values, token, VerifyList(), and Warning.
Referenced by execute_side_effects().
void CopyPrintOptions (PrintOptions * target, PrintOptions * source)
Copies a PrintOptions object.
Parameters
target The PrintOptions object to be overwritten.
source The PrintOptions object to copy.
void ParsePrintOptions (void)
Reads the global string printModeOptions and parses it to update the GlobalPrintOptions.
See also
printModeOptions
GlobalPrintOptions
References CL_MAX_LINE_LENGTH, cl_strcpy(), _print_option_rec_::number_lines, _print_option_rec_::print_border, _print_option_rec_::print_header, _print_option_rec_::print_tabular, _print_option_rec_::print_wrap, printModeOptions, silent, and token.
Referenced by execute_side_effects(), html_print_output(), and latex_print_output().
Variable Documentation
PrintMode GlobalPrintMode
Global print-mode setting.
Referenced by after_CorpusCommand(), catalog_corpus(), do_cat(), execute_side_effects(), print_group(), and printAlignedStrings().
PrintOptions GlobalPrintOptions
Global print-options: all booleans initially set to false.
Referenced by ascii_print_output(), catalog_corpus(), html_print_aligned_line(), html_print_corpus_header(), html_print_field(), html_print_output(), latex_print_field(), latex_print_output(), print_corpus_info_header(), and print_option_value().