CWB: cqp/sgml-print.h File Reference
sgml-print.h File Reference
#include <stdio.h>
#include "../cl/bitfields.h"
#include "corpmanag.h"
#include "context_descriptor.h"
#include "print-modes.h"
#include "groups.h"
Functions
void sgml_print_aligned_line (FILE *stream, char *attribute_name, char *line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) following an SGML open-tag.
void sgml_print_corpus_header (CorpusList *cl, FILE *outfd)
void sgml_print_output (CorpusList *cl, FILE *outfd, int interactive, ContextDescriptor *cd, int first, int last)
void sgml_print_group (Group *group, int expand, FILE *fd)
Variables
PrintDescriptionRecord SGMLPrintDescriptionRecord
Function Documentation
void sgml_print_aligned_line (FILE * stream, char * attribute_name, char * line)
Prints a line of text (which will have been previously exrtracted from a corfpus linked to the present corpus by an a-attribute) following an SGML open-tag.
The structure is <align name="$att_name">$line_data And the whole thing is terminated by EOL (note, no close tag as we;'d have in XML!)
Parameters
stream Destination for the output.
attribute_name The name of the aligned corpus: printed in the "align" tag as an SGML attribute.
line Character data of the line of aligned-corpus data to print. This is treated as opaque.
References sgml_puts(), and SUBST_NONE.
Referenced by printAlignedStrings().
void sgml_print_corpus_header (CorpusList * cl, FILE * outfd)
References CD, cl::corpus, cl::mother_name, TCorpus::name, cl::name, passwd, TCorpus::registry_name, sgml_print_context(), and cl::size.
Referenced by print_corpus_info_header().
void sgml_print_group (Group * group, int expand, FILE * fd)
References cl_broken_pipe, _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), _grouptable::nr_cells, _id_cnt_mapping::s, sgml_puts(), SUBST_ALL, and _id_cnt_mapping::t.
Referenced by print_group().
void sgml_print_output (CorpusList * cl, FILE * outfd, int interactive, ContextDescriptor * cd, int first, int last)
References _print_descr_rec_::AfterConcordance, _print_descr_rec_::AfterLine, _context_description_block::alignedCorpora, _Attribute::any, _attrbuf::attribute, _context_description_block::attributes, _print_descr_rec_::BeforeConcordance, _print_descr_rec_::BeforeLine, CD, cl_broken_pipe, compose_kwic_line(), ConcLineHorizontal, cl::corpus, _Range::end, _ConcLineField::end_position, KeywordField, cl::keywords, last, line, _attlist::list, MatchEndField, MatchField, _attrbuf::next, NoField, printAlignedStrings(), _context_description_block::printStructureTags, cl::range, SGMLPrintDescriptionRecord, cl::size, cl::sortidx, _Range::start, _ConcLineField::start_position, _attrbuf::status, TargetField, cl::targets, and _ConcLineField::type.
Referenced by print_output().
Variable Documentation
PrintDescriptionRecord SGMLPrintDescriptionRecord
Referenced by printAlignedStrings(), and sgml_print_output().