CWB: cqp/targets.h File Reference
targets.h File Reference
#include "eval.h"
#include "corpmanag.h"
Typedefs
typedef enum _search_strategy SearchStrategy
Enumerations
enum _search_strategy {
SearchLeftmost, SearchRightmost, SearchNearest, SearchFarthest,
SearchNone
}
Functions
SearchStrategy string_to_strategy (char *s)
int set_target (CorpusList *corp, FieldType goal, FieldType source)
int evaluate_target (CorpusList *corp, FieldType goal, FieldType base, int inclusive, SearchStrategy strategy, Constrainttree constr, enum ctxtdir direction, int units, char *attr_name)
int evaluate_subset (CorpusList *corp, FieldType the_field, Constrainttree constr)
Typedef Documentation
typedef enum _search_strategy SearchStrategy
Enumeration Type Documentation
enum _search_strategy
Enumerator
SearchLeftmost
SearchRightmost
SearchNearest
SearchFarthest
SearchNone
Function Documentation
int evaluate_subset (CorpusList * corp, FieldType the_field, Constrainttree constr)
References cqp, cqpmessage(), _Range::end, eval_bool(), EvaluationIsRunning, install_signal_handler(), KeywordField, cl::keywords, line, MatchEndField, MatchField, NoField, progress_bar, progress_bar_message(), progress_bar_percentage(), cl::range, RangeSetop(), RReduce, cl::size, _Range::start, SUB, TargetField, cl::targets, TEMP, cl::type, Warning, and which_app.
Referenced by do_subset().
int evaluate_target (CorpusList * corp, FieldType goal, FieldType base, int inclusive, SearchStrategy strategy, Constrainttree constr, enum ctxtdir direction, int units, char * attr_name)
References ATT_POS, ATT_STRUC, ctxtsp::attrib, calculate_ranges(), CheckForInterrupts(), cl_calloc(), cl_free, cl::corpus, cqp, cqpmessage(), DEFAULT_ATT_NAME, ctxtsp::direction, _Range::end, Error, eval_bool(), EvaluationIsRunning, False, find_attribute, install_signal_handler(), KeywordField, cl::keywords, left, line, MatchEndField, MatchField, MAX, cl::mother_name, progress_bar, progress_bar_clear_line(), progress_bar_message(), progress_bar_percentage(), cl::range, RangeSort(), right, SearchFarthest, SearchLeftmost, SearchNearest, SearchRightmost, cl::size, ctxtsp::size, _Range::start, structure, TargetField, cl::targets, touch_corpus(), ctxtsp::type, Warning, which_app, and word.
Referenced by do_set_complex_target().
int set_target (CorpusList * corp, FieldType goal, FieldType source)
References cl_free, cl_malloc(), cqpmessage(), _Range::end, Error, KeywordField, cl::keywords, MatchEndField, MatchField, cl::name, NoField, cl::range, RangeSort(), cl::size, _Range::start, TargetField, cl::targets, and touch_corpus().
Referenced by do_set_target().
SearchStrategy string_to_strategy (char * s)
References cqpmessage(), SearchFarthest, SearchLeftmost, SearchNearest, SearchNone, SearchRightmost, and Warning.