#! /usr/bin/bash

################################################################
# INSTALL CQPWEB, CWB and PERL API
################################################################

# Extract source files
cd /tmp/
tar -xzf cwb.tar.gz
tar -xzf cqpweb.tar.gz

# Move CQPweb files to Apache's web root and adjust permissions
mv /tmp/CQPweb*/* /var/www/html
chown -R www-data:www-data /var/www/html
rm /var/www/html/index.html

# Install the CWB
cd /tmp/cwb*src
./install-scripts/install-linux

# Build and install Perl API
cd /tmp/perl
make install
make test

# Remove source files since they are not further needed
rm -rf /tmp/CQPweb* /tmp/cwb* /tmp/perl

# Create the data directories specified in CQPWeb's config, make Apache their owner and give "all" readwrite-access
mkdir -p /cqpweb_files
cd /cqpweb_files
mkdir data registry temp uploads databases
chown -R www-data:www-data /cqpweb_files
chmod -R a+rwx /cqpweb_files

################################################################
# Configure MySQL
################################################################

# This is a manual execution of mysql_secure_installation which
# sets a new password for MySQL's root user, removes anonymous
# users, disables remote login for root, removes test databases
# and flushes changes to MySQL's privilege tables
usermod -d /var/lib/mysql/ mysql # amend mysql user home 
service mysql start
mysql -sfu root << EOF
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root_password';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
EOF
service mysql stop
# Set the place for MySQL database creation to the centralized cqpweb_files directory
sed -i "/datadir */c\\datadir	= /cqpweb_files/databases" /etc/mysql/mysql.conf.d/mysqld.cnf
