=head1 NAME

cqpcl - The CWB Corpus Query Processor (B<depracated> commandline-only version)

=head1 SYNOPSIS

B<cqpcl> [-hvmscixS] [-D I<corpus>] [-r I<registry_dir>]
    [-l I<data_dir>] [-I I<init_file>] [-M I<macro_file>]
    [-W I<n>] [-L I<n>] [-R I<n>] [-b I<n>] [-d I<mode>]
    ( [-E I<variable>] | 'I<command>' ... )

=head1 DESCRIPTION

B<Use of this command-line version of CQP is deprecated>, due to security issues and problems with shell metacharacters.
B<It may be omitted from future releases of the CWB.>  The recommended methods for batch
processing with CQP are (a) to run B<cqp> as a slave process in the background (which is facilitated by
the C<-c> option and interface packages for various programming languages), or (b) to read an automatically
generated CQP script file with the C<-f> option.

Given B<cqpcl>'s depracation, this manual will not longer be updated (after summer 2011).

=head1 OPTIONS (see also man cqp)

 -h           help
 -v           version and copyright information
 -r dir       use <dir> as default registry
 -l dir       store/load subcorpora in <dir>
 -I file      read <file> as init file
 -M file      read macro definitions from <file>
 -m           disable macro expansion
 -E variable  execute query in $(<variable>)
 -s           auto subquery mode
 -c           child process mode
 -i           print matching ranges only (binary output)
 -W num       show <num> chars to the left & right of match
 -L num       show <num> chars to the left of match
 -R num       show <num> chars to the right of match
 -D corpus    set default corpus to <corpus>
 -b num       set hard boundary for kleene star to <num> tokens
 -S           SIG_PIPE handler toggle
 -x           insecure mode (when run SETUID)
 -d mode      activate/deactivate debug mode, where <mode> is one of: 
    [ ShowSymtab, ShowPatList, ShowEvaltree, ShowDFA, ShowCompDFA,   ]
    [ ShowGConstraints, SymtabDebug, TreeDebug, CLDebug,             ]
    [ EvalDebug, InitialMatchlistDebug, DebugSimulation,             ]
    [ VerboseParser, ParserDebug, ParseOnly, SearchDebug, MacroDebug ]
    [ ALL (activate all modes except ParseOnly)                      ]

=head1 ENVIRONMENT

B<cqpcl> uses the same environment variables as B<cqp>.

=head1 SEE ALSO

L<cqp>, L<cqpserver>, L<cwb-align>, L<cwb-align-show>, L<cwb-align-encode>, L<cwb-align-decode>, L<cwb-atoi>, L<cwb-compress-rdx>,
L<cwb-config>, L<cwb-decode-nqrfile>, L<cwb-decode>, L<cwb-describe-corpus>, L<cwb-encode>, L<cwb-huffcode>,
L<cwb-itoa>, L<cwb-lexdecode>, L<cwb-makeall>, L<cwb-scan-corpus>, L<cwb-s-decode>, L<cwb-s-encode>.

=head1 COPYRIGHT

B<IMS Open Corpus Workbench (CWB)> L<http://cwb.sourceforge.net/>

Copyright (C) 1993-2006 by IMS, University of Stuttgart

Copyright (C) 2007- by the respective contributers (see file F<AUTHORS>)

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details
(in the file F<COPYING>, or available via WWW at
L<http://www.gnu.org/copyleft/gpl.html>).

=cut

