=head1 NAME

cwb-itoa - Decode uncompressed binary CWB data file to ASCII numbers

=head1 SYNOPSIS

B<cwb-itoa> [-nl] I<file>

=head1 DESCRIPTION


Reads 32-bit integers in network format from CWB binary data file I<file> 
or from standard input and prints the values as ASCII numbers on standard output (one number per line).


=head1 OPTIONS

Please note that the CWB utilities do not currently support GNU-style C<--long-options>.

=over 4

=item B<-n>  

Read integers in network format (big endian, the default).

=item B<-l>  

Read integers in little endian format.

=item B<-h>

Displays B<cwb-itoa>'s help message, with short information about the usage of the command line options. 
After the usage message is printed, B<cwb-itoa> will exit.

=back


=head1 SEE ALSO

L<cwb-atoi>, L<cqp>, L<cwb-describe-corpus>.


=head1 COPYRIGHT

B<IMS Open Corpus Workbench (CWB)> L<http://cwb.sourceforge.net/>

Copyright (C) 1993-2006 by IMS, University of Stuttgart

Copyright (C) 2007- by the respective contributers (see file F<AUTHORS>)

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details
(in the file F<COPYING>, or available via WWW at
L<http://www.gnu.org/copyleft/gpl.html>).

=cut

